const RouteRules = {
  loginPage: "/",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password/:token",
  dashboard: "/dashboard",
  accountSetting: "/account-setting",
  cretificates: "/certificate",
  organization: "/organization",
  organizationView: "/orgView",
  organizationEdit: "/orgEdit",
  organizationAdd: "/orgAdd",
  addCertificate: "/addCert",
  previewCertificate: "/prevCert",
  manageRecipient: "/manageReci",
  addRecipient: "/addReci",
  updateRecipient: "/updateReci",
  userLogin: "/user-login",
  userDashBoard: "/userDashboard",
  userCertificate: "/userCertificate",
  viewApproval: "/viewApproval",
  viewRequest: "/viewRequest",
  fontCreate: "/fontCreate",
  fontMaster: "/fontMaster",
  poc: "/poc",
};
export default RouteRules;
